# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/x4s3vaa7y4x8m8v8zsjjv0cdk91rhk6q-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- beep 'afplay /System/Library/Sounds/Glass.aiff'
    abbr --add -- cat bat
    abbr --add -- gcps 'gcloud config set project $(gcloud projects list --format="value(projectId)" | fzf) && echo -e "\nYour current config is:\n" && gcloud config list'
    abbr --add -- getrepo 'ghq get'
    abbr --add -- la 'eza -T -L 1 -a -l --icons'
    abbr --add -- ls 'eza --icons --git'
    abbr --add -- lt 'eza -T -L 3 -a --icons'
    abbr --add -- lta 'eza -T -L 3 -a -l --icons'
    abbr --add -- repos 'cd $(ghq root)/$(ghq list | fzf)'
    abbr --add -- workspace 'cd $(ghq root)/$(ghq list | fzf) && code --add .'

    # Aliases

    # Interactive shell initialisation
    # Nix PATH
    fish_add_path /nix/var/nix/profiles/default/bin
    fish_add_path ~/.nix-profile/bin

    # Antigravity
    fish_add_path ~/.antigravity/antigravity/bin

    # oh-my-posh
    oh-my-posh init fish --config bubblesextra | source

    if set -q GHOSTTY_RESOURCES_DIR
        source "$GHOSTTY_RESOURCES_DIR/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/snrsw/.local/share/fish/home-manager/generated_completions" $post
    end

    /nix/store/jvqli6w4plrjipvq1zs2k096rmiq5a3j-direnv-2.37.1/bin/direnv hook fish | source

end
