done:
  max: 1000
  conditions:
  - merged
  - is_issue && closed
  - closed && author contains '[bot]'
read:
  max: 1000
  conditions:
  - is_release
  - author contains '[bot]' && me not in reviewers
  - is_pull_request && me not in reviewers && approved
open:
  max: 1
  conditions:
  - "is_pull_request && me in reviewers && passed && !approved && open && !draft"
  - is_pull_request && author == me
list:
  max: 1000
  conditions:
  - unread
